name: rover-backend

services:
  rover-db:
    image: postgres:15
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT_EXPOSE:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    # Tambahkan network di sini agar DB bisa diakses internal ✅
    networks:
      - rover-app-network
    mem_limit: 512m
    cpus: "0.5"

  backend:
    image: kayabaakihiko13/rover-backend-fastapi
    container_name: ${BE_CONTAINER_NAME:-backend-rover-be-dev}
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - MODEL_PATH=${MODEL_PATH}
      - LABEL_PATH=${LABEL_PATH}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_STARTTLS=${MAIL_STARTTLS}
      - MAIL_SSL_TLS=${MAIL_SSL_TLS}
      - SUPERADMIN_EMAIL=${SUPERADMIN_EMAIL}
      - SUPERADMIN_USERNAME=${SUPERADMIN_USERNAME}
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
      - CORS_FE_ORIGINS=${CORS_FE_ORIGINS}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./weights:/app/weights
    # Perbaiki: network -> networks ✅
    networks:
      - rover-app-network
    depends_on:
      rover-db:
        condition: service_healthy
    mem_limit: 512m
    cpus: "0.5"

networks:
  rover-app-network:
    name: rover-app-network # Memastikan nama network fix 'rover-app-network'
    driver: bridge

volumes:
  postgres_data: